version: "3.8"

services:
  glance:
    image: glanceapp/glance:latest
    volumes:
      - ./glance.yml:/app/glance.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2121:8080
