name: Build and deploy glance.bini.io

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.SSH_KEY }}
          envs: DATABASE_URL,DATABASE_USERNAME,DATABASE_PASSWORD,GITHUB_TOKEN,GITHUB_ACTOR,IMAGE_ID
          script: |
            sudo rm -rf /data/glance
            sudo mkdir -p /data/glance
            sudo chown deploy:deploy /data/glance
            cd /data
            git clone https://github.com/${{ github.repository }}.git
            cd glance
            echo "Compose file:"
            cat docker-compose.yml
            sudo docker-compose down
            sudo docker container prune -f
            sudo docker image prune -af
            sudo docker-compose pull
            sudo docker-compose up -d
